### ISSUE TITLE
error in imap section

### ISSUE THREAD

**Issue by BattleTaleGH** [hendrikbgr/YandexMail-Account-Creator#56] opened 2021-08-06 04:06 UTC
Hi guys,
there is issue (probably with adding imap etc)

error:
`Traceback (most recent call last):
  File "creator.py", line 311, in <module>
    wait.until(EC.element_to_be_clickable(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:`

**Comment by hendrikbgr** [comment] 2021-08-12 09:02
This issue got fixed in the latest version (git pull or redownload)

**Closed by hendrikbgr** 2021-08-12 09:02 UTC

**Comment by jacoballen55** [comment] 2021-08-20 06:13
I guess the issue is not fixed in the latest version as well. I am using the latest one. 

Traceback (most recent call last):
  File "C:\Users\JacobTVM\Downloads\YandexMail-Account-Creator-master\creator.py", line 299, in <module>
    wait.until(EC.element_to_be_clickable(
  File "C:\Users\JacobTVM\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by jacoballen55** [comment] 2021-08-20 06:18
Also getting another error saying invalid session id
